import {
  INSTAGRAM_PROFILE,
  LINKEDIN_PROFILE,
  getPublicProfileByUsername,
} from '@/lib/mockData'
import type {
  AirlineHighlight,
  ContactChannel,
  CorporateHighlight,
  GuestbookEntry,
  HeroTheme,
  InstagramProfile,
  LinkedInProfile,
  PublicProfile,
  ReputationKeyword,
  UserState,
} from '@/types'

type NormalizedLinkedInProfile = LinkedInProfile & {
  previewImage: string
}

type NormalizedPublicProfile = PublicProfile & {
  instagram: InstagramProfile
  linkedin: NormalizedLinkedInProfile
  heroTheme: HeroTheme
  contactChannels: ContactChannel[]
  corporateHighlight: CorporateHighlight
  airlineHighlight: AirlineHighlight
  reputationKeywords: ReputationKeyword[]
  guestbook: GuestbookEntry[]
}

const PUBLIC_PROFILE_FALLBACKS: {
  instagram: InstagramProfile
  linkedin: NormalizedLinkedInProfile
  heroTheme: HeroTheme
  contactChannels: ContactChannel[]
  corporateHighlight: CorporateHighlight
  airlineHighlight: AirlineHighlight
  reputationKeywords: ReputationKeyword[]
  guestbook: GuestbookEntry[]
} = {
  // TODO(real API): Replace with the connected Instagram account payload from the public profile detail response.
  instagram: {
    username: INSTAGRAM_PROFILE.username,
    profileUrl: INSTAGRAM_PROFILE.profileUrl,
    aiSummary: INSTAGRAM_PROFILE.aiSummary,
    posts: INSTAGRAM_PROFILE.posts,
  },
  // TODO(real API): Replace with the connected LinkedIn account payload plus the latest preview asset generated by the backend.
  linkedin: {
    profileUrl: LINKEDIN_PROFILE.profileUrl,
    aiSummary: LINKEDIN_PROFILE.aiSummary,
    previewImage: '/images/linkedsample.png',
  },
  // TODO(real API): Replace with per-user profile branding/theme fields saved from profile customization settings.
  heroTheme: {
    cover: 'from-[#B69B8B] via-[#836F66] to-[#121212]',
    avatar: 'from-[#DCC5B6] to-[#8F7265]',
  },
  // TODO(real API): Replace with only the contact channels that are public in the user's visibility settings.
  contactChannels: [],
  // TODO(real API): Replace with verified corporate registry aggregates for active companies and operating years.
  corporateHighlight: {
    companyCount: 1,
    years: 4,
    summary: '창업 4년차 · 정상 운영 중 · 폐업 이력 없음',
    companies: [
      { name: 'Byro Studio', startYear: 2022, endYear: null, years: 4, status: '정상 운영' },
    ],
  },
  // TODO(real API): Replace with airline loyalty integrations or verified membership summaries.
  airlineHighlight: {
    tierSummary: '대한항공 모닝캄',
    badgeLevel: 'business_traveler',
    airlines: [{ name: '대한항공', tier: '모닝캄' }],
  },
  // TODO(real API): Replace with aggregated reputation keyword counts returned by the public reputation summary API.
  reputationKeywords: [],
  // TODO(real API): Replace with the public guestbook feed for the profile owner.
  guestbook: [],
}

function buildEditableOwnerProfile(
  username: string,
  baseProfile: PublicProfile,
  user?: UserState | null,
): PublicProfile {
  if (!user || user.linkId !== username) {
    return baseProfile
  }

  // TODO(real API): Owner mode should merge a server profile payload with the user's editable draft, not local store-only fields.
  return {
    ...baseProfile,
    name: user.name,
    linkId: user.linkId,
    title: user.title,
    school: user.school,
    bio: user.bio,
    selectedKeywords: user.selectedKeywords,
    avatarColor: user.avatarColor ?? baseProfile.avatarColor,
    avatarImage: user.avatarImage || baseProfile.avatarImage,
    contactChannels: user.contactChannels ?? baseProfile.contactChannels,
  }
}

export function getNormalizedPublicProfile({
  username,
  user,
}: {
  username: string
  user?: UserState | null
}): NormalizedPublicProfile {
  // TODO(real API): Replace this mock selector with a public-profile detail query keyed by `username`.
  const baseProfile = getPublicProfileByUsername(username) as PublicProfile
  const rawProfile = buildEditableOwnerProfile(username, baseProfile, user)
  const instagram = rawProfile.instagram
  const linkedin = rawProfile.linkedin

  return {
    ...rawProfile,
    instagram: {
      ...(instagram ?? {}),
      username: instagram?.username ?? PUBLIC_PROFILE_FALLBACKS.instagram.username,
      profileUrl: instagram?.profileUrl ?? PUBLIC_PROFILE_FALLBACKS.instagram.profileUrl,
      aiSummary: instagram?.aiSummary ?? PUBLIC_PROFILE_FALLBACKS.instagram.aiSummary,
      posts: instagram?.posts ?? PUBLIC_PROFILE_FALLBACKS.instagram.posts,
    },
    linkedin: {
      ...(linkedin ?? {}),
      profileUrl: linkedin?.profileUrl ?? PUBLIC_PROFILE_FALLBACKS.linkedin.profileUrl,
      aiSummary: linkedin?.aiSummary ?? PUBLIC_PROFILE_FALLBACKS.linkedin.aiSummary,
      previewImage: linkedin?.previewImage ?? PUBLIC_PROFILE_FALLBACKS.linkedin.previewImage,
    },
    heroTheme: rawProfile.heroTheme ?? PUBLIC_PROFILE_FALLBACKS.heroTheme,
    contactChannels: rawProfile.contactChannels ?? PUBLIC_PROFILE_FALLBACKS.contactChannels,
    corporateHighlight: rawProfile.corporateHighlight ?? PUBLIC_PROFILE_FALLBACKS.corporateHighlight,
    airlineHighlight: rawProfile.airlineHighlight ?? PUBLIC_PROFILE_FALLBACKS.airlineHighlight,
    reputationKeywords: rawProfile.reputationKeywords ?? PUBLIC_PROFILE_FALLBACKS.reputationKeywords,
    guestbook: rawProfile.guestbook ?? PUBLIC_PROFILE_FALLBACKS.guestbook,
  }
}
